// prettier-ignore
const ES = {
  "Address has been copied to the clipboard": "La dirección se ha copiado al portapapeles",
  "Amount": undefined,
  "An account with the same email exists already": undefined,
  "Cancel": "Cancelar",
  "Click QR code to copy": "Toque el código QR para copiar",
  "Close": "Cerrar",
  "Color Theme": undefined,
  "Confirm": "Confirmar",
  "Contacts": "Contactos",
  "Create Account": undefined,
  "Create new account": undefined,
  "Current Balance": "Saldo actual",
  "Dark mode": undefined,
  "Default (OS)": "Predeterminado (OS)",
  "Description": "Descripción",
  "Email": "Correo electrónico",
  "Email Support": "Soporte de contacto",
  "English": "Inglés",
  "Enter amount": "Ingrese cantidad",
  "Enter amount and destination": "Ingrese cantidad y dirección",
  "Enter your phone number and we'll text you an access code": "Ingrese su número de teléfono y le enviaremos un mensaje de texto con un código de acceso",
  "Fee": "Tarifa",
  "First Name": undefined,
  "Flexible Amount Invoice": "Factura con cantidad flexible",
  "From": "Desde",
  "Generate New Invoice": "Generar una factura nueva",
  "Generate new invoice": "Generar una factura nueva",
  "Generate new invoice for %{amount}": "Generar una factura nueva por %{amount}",
  "Generating Invoice...": "Generando factura...",
  "Hash": undefined,
  "History": "Historial",
  "Home": "Inicio",
  "How much would you like to send?": undefined,
  "Invaild email or password": undefined,
  "Invalid QR Code": undefined,
  "Invalid verification. Please try again": undefined,
  "Invite": undefined,
  "Invoice Amount": "Cantidad de la factura",
  "Invoice Expired": "Factura expirada",
  "Invoice has been copied to the clipboard": undefined,
  "Invoice is already paid": undefined,
  "Invoice value is now %{value}": undefined,
  "Language": "Idioma",
  "Last Name": undefined,
  "Light mode": undefined,
  "Lightning": undefined,
  "Link has been copied to the clipboard": undefined,
  "Load more transactions": "Obtener más transacciones",
  "Login": "Iniciar sesión",
  "Login to send": undefined,
  "Logout": "Cerrar sesión",
  "New Password": undefined,
  "Next": "Siguiente",
  "No Contacts": undefined,
  "No transactions": "No transacciones",
  "Note": undefined,
  "Note or Label": undefined,
  "OnChain": undefined,
  "Password": undefined,
  "Password is too short": undefined,
  "Payment amount exceeds balance of %{balance} sats": "Cantidad excede su saldo de por %{balance}",
  "Payment failed": undefined,
  "Phone number is too long": undefined,
  "Phone number is too short": undefined,
  "Please try again later": undefined,
  "Please try again later.": undefined,
  "Portuguese": "Portugués",
  "Powered By": undefined,
  "Previous months": "Meses anteriores",
  "Receive": "Recibir",
  "Receive Bitcoin": "Recibir Bitcoin",
  "Receive another payment": undefined,
  "Received from": "Recibido de",
  "Recent Transactions": "Las transacciones",
  "Recover Account": undefined,
  "Recover your account": undefined,
  "Refresh": undefined,
  "Reload Application": undefined,
  "Save": undefined,
  "Scan QR code": "Escanear QR",
  "Send": "Enviar",
  "Send Bitcoin": "Enviar Bitcoin",
  "Send Payment": "Enviar Pago",
  "Send another payment": undefined,
  "Sending bitcoin to": undefined,
  "Sent to": "Enviado a",
  "Set Amount": undefined,
  "Set a note for the receiver here (optional)": undefined,
  "Set a note for the sender here (optional)": undefined,
  "Set a note/label": "Agregar una nota",
  "Set invoice value in %{currency}": undefined,
  "Set value to send in %{currency}": undefined,
  "Settings": "Configuración",
  "Share Bitcoin Address": "Compartir la dirección de Bitcoin",
  "Share Lightning Address": "Compartir la dirección de Lightning",
  "Sorry, we appear to be having issues loading the application data. If the problem persists, please contact support.": undefined,
  "Spanish": "Español",
  "This month": "Este mes",
  "To": "Enviado a",
  "To confirm your phone number, enter the code we just sent you on %{phoneNumber}": "Ingrese su número de teléfono, y le enviaremos un mensaje de texto con un código de acceso.",
  "Today": "Hoy",
  "Transaction List": undefined,
  "Transactions with %{contactUsername}": "Las transacciones con %{contactUsername}",
  "Update Invoice": "Actualizar Factura",
  "Use a Bitcoin on-chain address": "Use una dirección en cadena de Bitcoin",
  "Use a Lightning invoice": "Use una factura Lightning",
  "Username": "Nombre de usuario",
  "Verify Account": undefined,
  "Verify you are human": undefined,
  "Waiting for payment confirmation...": undefined,
  "What for": undefined,
  "Yesterday": "Ayer",
  "You can't send to yourself": undefined,
  "You can’t send a payment to yourself": "No puede enviar un pago a usted mismo",
  "You successfully recovered your account. Please change your password.": undefined,
  "Your account verification is still pending": undefined,
  "Your email address has been verified": undefined,
  "username, invoice, or address": undefined,
} as const

export type TranslationKey = keyof typeof ES

export default ES
