const ES = {
  "Address has been copied to the clipboard": "",
  "Click QR code to copy": "",
  "Close": "",
  "Current Balance": "",
  "Enter amount and destination": "",
  "Enter your phone number and we'll text you an access code": "",
  "Generate new invoice for %{amount}": "",
  "Generate New Invoice": "",
  "Invaild verification. Please try again": "",
  "Invalid QR Code": "",
  "Invoice Expired...": "",
  "Invoice has been copied to the clipboard": "",
  "Invoice value is now %{value}": "",
  "Lightning": "",
  "Login to send": "",
  "Login": "",
  "Logout": "",
  "Not able to generate invoice.": "",
  "OnChain": "",
  "Payment amount exceeds balance of %{balance} sats": "",
  "Please try again later.": "",
  "Powered By": "",
  "Receive Bitcoin": "",
  "Scan QR code": "",
  "Send Bitcoin": "",
  "Set a note for the receiver here (optional)": "",
  "Set a note for the sender here (optional)": "",
  "Set invoice value in %{currency}": "",
  "Set value to send in %{currency}": "",
  "To confirm your phone number, enter the code we just sent you on %{phoneNumber}": "",
  "username or invoice": "",
  "Verify you are human": "",
  "Waiting for payment confirmation...": "",
} as const

export type VALID_KEYS = keyof typeof ES

export default ES
