// prettier-ignore
const ES = {
  "Address has been copied to the clipboard": undefined,
  "Activate Wallet": undefined,
  "Address": undefined,
  "Amount is required": undefined,
  "Back": undefined,
  "Bank": undefined,
  "Bitcoin Price": undefined,
  "Bitcoin": undefined,
  "Cancel": undefined,
  "Cash Account": undefined,
  "Click QR code to copy": undefined,
  "Close": undefined,
  "Coming soon!": undefined,
  "Confirm": undefined,
  "Current Balance": undefined,
  "Date": undefined,
  "Description": undefined,
  "Domain": undefined,
  "Email Support": undefined,
  "Email": undefined,
  "Enter amount and destination": undefined,
  "Enter your phone number and we'll text you an access code": undefined,
  "Error loading transactions": undefined,
  "Error": undefined,
  "Export transactions as CSV": undefined,
  "Fatal": undefined,
  "fee": undefined,
  "Fee": undefined,
  "Fees (sats)": undefined,
  "Fees (USD)": undefined,
  "Fees": undefined,
  "First Name": undefined,
  "Generate new invoice for %{amount}": undefined,
  "Generate New Invoice": undefined,
  "Home": undefined,
  "hour": undefined,
  "Hash": undefined,
  "hours": undefined,
  "Invaild country code": undefined,
  "Invaild verification. Please try again": undefined,
  "Invalid phone number": undefined,
  "Invalid QR Code": undefined,
  "Invoice Expired...": undefined,
  "Invoice has been copied to the clipboard": undefined,
  "Invoice is already paid": undefined,
  "Invoice value is now %{value}": undefined,
  "Invoice": undefined,
  "Language preference": undefined,
  "Language": undefined,
  "Last Name": undefined,
  "Later": undefined,
  "Lightning": undefined,
  "Log Out": undefined,
  "Login to send": undefined,
  "Login": undefined,
  "Logout": undefined,
  "minutes": undefined,
  "Next": undefined,
  "No connection": undefined,
  "No transactions": undefined,
  "Not able to generate invoice.": undefined,
  "Note": undefined,
  "Notification": undefined,
  "OK": undefined,
  "OnChain": undefined,
  "Open Wallet": undefined,
  "Payment amount exceeds balance of %{balance} sats": undefined,
  "Payment failed": undefined,
  "Phone number is too long": undefined,
  "Phone number is too short": undefined,
  "Phone Number": undefined,
  "Please try again later.": undefined,
  "Powered By": undefined,
  "Receive another payment": undefined,
  "Receive Bitcoin": undefined,
  "Recent Transactions": undefined,
  "Reload Application": undefined,
  "Restart": undefined,
  "sats": undefined,
  "Scan QR code": undefined,
  "Search": undefined,
  "Security": undefined,
  "Send another payment": undefined,
  "Send Bitcoin": undefined,
  "Send Payment": undefined,
  "Send": undefined,
  "Set a note for the receiver here (optional)": undefined,
  "Set a note for the sender here (optional)": undefined,
  "set an amount": undefined,
  "Set invoice value in %{currency}": undefined,
  "Set value to send in %{currency}": undefined,
  "Share Bitcoin Address": undefined,
  "Share Lightning Invoice": undefined,
  "Share": undefined,
  "Sorry, we appear to be having issues loading the application data. If the problem persists, please contact support.": undefined,
  "Success!": undefined,
  "To confirm your phone number, enter the code we just sent you on %{phoneNumber}": undefined,
  "To": undefined,
  "Total": undefined,
  "Transaction Details": undefined,
  "Transactions": undefined,
  "Try Again": undefined,
  "Type": undefined,
  "Username is required": undefined,
  "username or invoice": undefined,
  "Username": undefined,
  "Validate your phone to open your wallet": undefined,
  "Verify you are human": undefined,
  "Waiting for payment confirmation...": undefined,
  "You can't send to yourself": undefined,
  "You have been logged out.": undefined,
  "You received": undefined,
  "You spent": undefined,
  "Your session has expired. Please log in again.": undefined,
  "Received from": undefined,
  "Sent to": undefined,
} as const

export type VALID_KEYS = keyof typeof ES

export default ES
