// prettier-ignore
const ES = {
  "Address has been copied to the clipboard": undefined,
  "Click QR code to copy": undefined,
  "Close": undefined,
  "Current Balance": undefined,
  "Email Support": undefined,
  "Enter amount and destination": undefined,
  "Enter your phone number and we'll text you an access code": undefined,
  "Generate new invoice for %{amount}": undefined,
  "Generate New Invoice": undefined,
  "Home": undefined,
  "Invaild country code": undefined,
  "Invaild verification. Please try again": undefined,
  "Invalid phone number": undefined,
  "Invalid QR Code": undefined,
  "Invoice Expired...": undefined,
  "Invoice has been copied to the clipboard": undefined,
  "Invoice is already paid": undefined,
  "Invoice value is now %{value}": undefined,
  "Lightning": undefined,
  "Login to send": undefined,
  "Login": undefined,
  "Logout": undefined,
  "No transactions": undefined,
  "Not able to generate invoice.": undefined,
  "OnChain": undefined,
  "Payment amount exceeds balance of %{balance} sats": undefined,
  "Payment failed": undefined,
  "Phone number is too long": undefined,
  "Phone number is too short": undefined,
  "Please try again later.": undefined,
  "Powered By": undefined,
  "Receive another payment": undefined,
  "Receive Bitcoin": undefined,
  "Recent Transactions": undefined,
  "Reload Application": undefined,
  "Scan QR code": undefined,
  "Send another payment": undefined,
  "Send Bitcoin": undefined,
  "Send Payment": undefined,
  "Set a note for the receiver here (optional)": undefined,
  "Set a note for the sender here (optional)": undefined,
  "Set invoice value in %{currency}": undefined,
  "Set value to send in %{currency}": undefined,
  "Sorry, we appear to be having issues loading the application data. If the problem persists, please contact support.": undefined,
  "To confirm your phone number, enter the code we just sent you on %{phoneNumber}": undefined,
  "username or invoice": undefined,
  "Verify you are human": undefined,
  "Waiting for payment confirmation...": undefined,
  "You can't send to yourself": undefined,
} as const

export type VALID_KEYS = keyof typeof ES

export default ES
