query main($isAuthenticated: Boolean!, $recentTransactions: Int) {
  globals {
    nodesIds
    network
    lightningAddressDomain
  }
  btcPrice {
    base
    offset
    currencyUnit
    formattedAmount
  }
  me @include(if: $isAuthenticated) {
    ...Me
  }
}
