#! Auto synced from Shared CI Resources repository
#! Don't change this file, instead change it in github.com/blinkbitcoin/concourse-shared

name: Audit

on:
  pull_request:
    branches: [main]

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      # Make the Nix-provided pnpm available to setup-node
      - name: Make pnpm available for caching
        run: |
          mkdir -p ~/.local/bin
          nix develop -c bash -c 'which pnpm > /tmp/pnpm_path'
          ln -sf $(cat /tmp/pnpm_path) ~/.local/bin/pnpm
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
      - run: nix develop -c pnpm install --frozen-lockfile
      - name: Run audit
        run: nix develop -c pnpm audit --prod --audit-level=high
