#! Auto synced from Shared CI Resources repository
#! Don't change this file, instead change it in github.com/blinkbitcoin/concourse-shared

name: "Check code"
on:
  pull_request:
    branches: [main]
    
jobs:
  check-code:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Install dependencies inside nix develop
        run: nix develop -c pnpm install

      - name: Run check code
        run: nix develop -c pnpm code:check
